### ISSUE TITLE
Cannot install the CONJScan plasmids package

### ISSUE THREAD

**Issue by Pirxtrurl** [macsy-models/CONJScan_plasmids#1]
Hello,

I am trying to install the CONJScan models for use with the Macsfinder v2.0rc7 tool. However, I had the following error when I tried to install the repository using Macsydata:

 Could not find version that satisfied 'CONJScan_plasmids'

Please, could you indicate to me how to install the CONJScan model?

Best regards,

Jorge Val-Calvo
Infection Medicine, University of Edinburgh

**Comment by bneron** [comment]
CONJScan_plasmids models are steel in development. 
as soon the package will be released and a version available, you could install it with macsydata.
